export const LeadStates = {
  NEW: 'NEW',
  IN_CONVERSATION: 'IN_CONVERSATION',
  QUALIFYING: 'QUALIFYING',
  QUALIFIED: 'QUALIFIED',
  PROPERTY_SHOWN: 'PROPERTY_SHOWN',
  INTERESTED: 'INTERESTED',
  VISIT_REQUESTED: 'VISIT_REQUESTED',
  AWAITING_BROKER_APPROVAL: 'AWAITING_BROKER_APPROVAL',
  VISIT_CONFIRMED: 'VISIT_CONFIRMED',
  VISIT_COMPLETED: 'VISIT_COMPLETED',
  CONVERTED: 'CONVERTED',
  LOST: 'LOST',
  INACTIVE_24H: 'INACTIVE_24H',
  INACTIVE_3D: 'INACTIVE_3D',
  INACTIVE_7D: 'INACTIVE_7D',
  DORMANT: 'DORMANT',
  RESURRECTED: 'RESURRECTED',
} as const

export type LeadState = typeof LeadStates[keyof typeof LeadStates]
